# Multiple imputation by chained equations (MICE)

In [2]:
# Cargar bibliotecas
import seaborn as sns
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [3]:
# Cargar el dataset de Titanic desde seaborn
titanic = sns.load_dataset('titanic')

In [4]:
# Mostrar primeros valores
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
# Check missing data
print(titanic.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [6]:
# Vamos a imputar los valores faltantes de la columna 'age' (edad)
# Seleccionamos un subconjunto de columnas para el ejemplo
data = titanic[['age', 'fare', 'pclass', 'sex']]

# Convertimos las variables categóricas en variables dummy (la variable 'sex' es categórica)
data = pd.get_dummies(data, drop_first=True)

data.head(20)

     age     fare  pclass  sex_male
0   22.0   7.2500       3      True
1   38.0  71.2833       1     False
2   26.0   7.9250       3     False
3   35.0  53.1000       1     False
4   35.0   8.0500       3      True
5    NaN   8.4583       3      True
6   54.0  51.8625       1      True
7    2.0  21.0750       3      True
8   27.0  11.1333       3     False
9   14.0  30.0708       2     False
10   4.0  16.7000       3     False
11  58.0  26.5500       1     False
12  20.0   8.0500       3      True
13  39.0  31.2750       3      True
14  14.0   7.8542       3     False
15  55.0  16.0000       2     False
16   2.0  29.1250       3      True
17   NaN  13.0000       2      True
18  31.0  18.0000       3     False
19   NaN   7.2250       3     False

In [7]:
# Crear el imputador MICE (IterativeImputer)
imputer = IterativeImputer(max_iter=10, random_state=0)

In [8]:
# Imputar los valores faltantes
data_imputed = pd.DataFrame(imputer.fit_transform(data), columns=data.columns)

In [9]:
# Mostrar los datos originales con valores faltantes
print("Datos originales (con valores faltantes):")
data.head(30)

Datos originales (con valores faltantes):

     age      fare  pclass  sex_male
0   22.0    7.2500       3      True
1   38.0   71.2833       1     False
2   26.0    7.9250       3     False
3   35.0   53.1000       1     False
4   35.0    8.0500       3      True
5    NaN    8.4583       3      True
6   54.0   51.8625       1      True
7    2.0   21.0750       3      True
8   27.0   11.1333       3     False
9   14.0   30.0708       2     False
10   4.0   16.7000       3     False
11  58.0   26.5500       1     False
12  20.0    8.0500       3      True
13  39.0   31.2750       3      True
14  14.0    7.8542       3     False
15  55.0   16.0000       2     False
16   2.0   29.1250       3      True
17   NaN   13.0000       2      True
18  31.0   18.0000       3     False
19   NaN    7.2250       3     False
20  35.0   26.0000       2      True
21  34.0   13.0000       2      True
22  15.0    8.0292       3     False
23  28.0   35.5000       1      True
24   8.0   21.0750       3     False
25  38.0   31.3875       3     False
26   NaN    7.2250       3      True
27  19.0  263.0000       1      True
28   NaN    7.8792       3     False
29   NaN    7.8958       3      True

In [10]:
# Mostrar los datos después de la imputación múltiple (MICE)
print("\nDatos después de la imputación múltiple (MICE):")
data_imputed.head(30)

Datos después de la imputación múltiple (MICE):

          age      fare  pclass  sex_male
0   22.000000    7.2500     3.0       1.0
1   38.000000   71.2833     1.0       0.0
2   26.000000    7.9250     3.0       0.0
3   35.000000   53.1000     1.0       0.0
4   35.000000    8.0500     3.0       1.0
5   26.082704    8.4583     3.0       1.0
6   54.000000   51.8625     1.0       1.0
7    2.000000   21.0750     3.0       1.0
8   27.000000   11.1333     3.0       0.0
9   14.000000   30.0708     2.0       0.0
10   4.000000   16.7000     3.0       0.0
11  58.000000   26.5500     1.0       0.0
12  20.000000    8.0500     3.0       1.0
13  39.000000   31.2750     3.0       1.0
14  14.000000    7.8542     3.0       0.0
15  55.000000   16.0000     2.0       0.0
16   2.000000   29.1250     3.0       1.0
17  33.850204   13.0000     2.0       1.0
18  31.000000   18.0000     3.0       0.0
19  22.070708    7.2250     3.0       0.0
20  35.000000   26.0000     2.0       1.0
21  34.000000   13.0000     2.0       1.0
22  15.000000    8.0292     3.0       0.0
23  28.000000   35.5000     1.0       1.0
24   8.000000   21.0750     3.0       0.0
25  38.000000   31.3875     3.0       0.0
26  26.127637    7.2250     3.0       1.0
27  19.000000  263.0000     1.0       1.0
28  22.046873    7.8792     3.0       0.0
29  26.103198    7.8958     3.0       1.0

# Exercise 1
Use MICE on the life-expectancy dataset to fill in missing values.
https://www.kaggle.com/datasets/kumarajarshi/life-expectancy-who

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [13]:
import os
import shutil
os.makedirs(os.path.expanduser('~/.kaggle'), exist_ok=True)
shutil.copy('/content/drive/MyDrive/kaggle/kaggle.json', '/root/.kaggle/kaggle.json')
!chmod 600 /root/.kaggle/kaggle.json

In [15]:
!kaggle datasets download -d kumarajarshi/life-expectancy-who

Dataset URL: https://www.kaggle.com/datasets/kumarajarshi/life-expectancy-who
License(s): other
Downloading life-expectancy-who.zip to /content
  0% 0.00/119k [00:00<?, ?B/s]
100% 119k/119k [00:00<00:00, 50.9MB/s]

In [16]:
import zipfile

with zipfile.ZipFile('life-expectancy-who.zip', 'r') as zip_ref:
    zip_ref.extractall('life_expectancy_data')

In [19]:
data_path = '/content/life_expectancy_data/Life Expectancy Data.csv'
data = pd.read_csv(data_path)
data.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [22]:
print(data.isnull().sum())

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [29]:
subset_columns = ['Life expectancy ', 'GDP', 'Adult Mortality', 'Schooling', 'Population', 'Total expenditure', 'Alcohol', 'Hepatitis B', 'Income composition of resources']
data_subset = data[subset_columns]
imputer = IterativeImputer(max_iter=10, random_state=0)
data_imputed = pd.DataFrame(imputer.fit_transform(data_subset), columns=data_subset.columns)

In [30]:
print("Original Data (with missing values):")
data_subset.head(30)

Original Data (with missing values):

,Life expectancy,GDP,Adult Mortality,Schooling,Population,Total expenditure,Alcohol,Hepatitis B,Income composition of resources
0,65.0,584.259210,263.0,10.1,33736494.0,8.16,0.01,65.0,0.479
1,59.9,612.696514,271.0,10.0,327582.0,8.18,0.01,62.0,0.476
2,59.9,631.744976,268.0,9.9,31731688.0,8.13,0.01,64.0,0.470
3,59.5,669.959000,272.0,9.8,3696958.0,8.52,0.01,67.0,0.463
4,59.2,63.537231,275.0,9.5,2978599.0,7.87,0.01,68.0,0.454
5,58.8,553.328940,279.0,9.2,2883167.0,9.20,0.01,66.0,0.448
6,58.6,445.893298,281.0,8.9,284331.0,9.42,0.01,63.0,0.434
7,58.1,373.361116,287.0,8.7,2729431.0,8.33,0.03,64.0,0.433
8,57.5,369.835796,295.0,8.4,26616792.0,6.73,0.02,63.0,0.415
9,57.3,272.563770,295.0,8.1,2589345.0,7.43,0.03,64.0,0.405
10,57.3,25.294130,291.0,7.9,257798.0,8.70,0.02,66.0,0.396
11,57.0,219.141353,293.0,6.8,24118979.0,8.79,0.02,67.0,0.381
12,56.7,198.728544,295.0,6.5,2364851.0,8.82,0.01,65.0,0.373
13,56.2,187.845950,3.0,6.2,21979923.0,7.76,0.01,64.0,0.341
14,55.3,117.496980,316.0,5.9,2966463.0,7.80,0.01,63.0,0.340
15,54.8,114.560000,321.0,5.5,293756.0,8.20,0.01,62.0,0.338
16,77.8,3954.227830,74.0,14.2,28873.0,6.00,4.60,99.0,0.762
17,77.5,4575.763787,8.0,14.2,288914.0,5.88,4.51,98.0,0.761
18,77.2,4414.723140,84.0,14.2,289592.0,5.66,4.76,99.0,0.759
19,76.9,4247.614380,86.0,14.2,2941.0,5.59,5.14,99.0,0.752
20,76.6,4437.178680,88.0,13.3,295195.0,5.71,5.37,99.0,0.738
21,76.2,494.358832,91.0,12.5,291321.0,5.34,5.28,99.0,0.725
22,76.1,4114.136545,91.0,12.2,2927519.0,5.79,5.79,98.0,0.721
23,75.3,437.539647,1.0,12.0,2947314.0,5.87,5.61,99.0,0.713
24,75.9,363.136850,9.0,11.6,29717.0,6.10,5.58,98.0,0.703
25,74.2,35.129300,99.0,11.4,2992547.0,5.86,5.31,98.0,0.696
26,73.5,279.142931,15.0,10.8,311487.0,6.12,5.16,98.0,0.685
27,73.0,2416.588235,17.0,10.9,326939.0,6.38,4.54,99.0,0.681
28,72.8,189.681557,18.0,10.7,339616.0,6.27,4.29,97.0,0.674
29,73.3,1453.642777,15.0,10.7,3511.0,6.30,3.73,96.0,0.670

In [31]:
print("\nData after MICE Imputation:")
data_imputed.head(30)

Data after MICE Imputation:

,Life expectancy,GDP,Adult Mortality,Schooling,Population,Total expenditure,Alcohol,Hepatitis B,Income composition of resources
0,65.0,584.259210,263.0,10.1,33736494.0,8.16,0.01,65.0,0.479
1,59.9,612.696514,271.0,10.0,327582.0,8.18,0.01,62.0,0.476
2,59.9,631.744976,268.0,9.9,31731688.0,8.13,0.01,64.0,0.470
3,59.5,669.959000,272.0,9.8,3696958.0,8.52,0.01,67.0,0.463
4,59.2,63.537231,275.0,9.5,2978599.0,7.87,0.01,68.0,0.454
5,58.8,553.328940,279.0,9.2,2883167.0,9.20,0.01,66.0,0.448
6,58.6,445.893298,281.0,8.9,284331.0,9.42,0.01,63.0,0.434
7,58.1,373.361116,287.0,8.7,2729431.0,8.33,0.03,64.0,0.433
8,57.5,369.835796,295.0,8.4,26616792.0,6.73,0.02,63.0,0.415
9,57.3,272.563770,295.0,8.1,2589345.0,7.43,0.03,64.0,0.405
10,57.3,25.294130,291.0,7.9,257798.0,8.70,0.02,66.0,0.396
11,57.0,219.141353,293.0,6.8,24118979.0,8.79,0.02,67.0,0.381
12,56.7,198.728544,295.0,6.5,2364851.0,8.82,0.01,65.0,0.373
13,56.2,187.845950,3.0,6.2,21979923.0,7.76,0.01,64.0,0.341
14,55.3,117.496980,316.0,5.9,2966463.0,7.80,0.01,63.0,0.340
15,54.8,114.560000,321.0,5.5,293756.0,8.20,0.01,62.0,0.338
16,77.8,3954.227830,74.0,14.2,28873.0,6.00,4.60,99.0,0.762
17,77.5,4575.763787,8.0,14.2,288914.0,5.88,4.51,98.0,0.761
18,77.2,4414.723140,84.0,14.2,289592.0,5.66,4.76,99.0,0.759
19,76.9,4247.614380,86.0,14.2,2941.0,5.59,5.14,99.0,0.752
20,76.6,4437.178680,88.0,13.3,295195.0,5.71,5.37,99.0,0.738
21,76.2,494.358832,91.0,12.5,291321.0,5.34,5.28,99.0,0.725
22,76.1,4114.136545,91.0,12.2,2927519.0,5.79,5.79,98.0,0.721
23,75.3,437.539647,1.0,12.0,2947314.0,5.87,5.61,99.0,0.713
24,75.9,363.136850,9.0,11.6,29717.0,6.10,5.58,98.0,0.703
25,74.2,35.129300,99.0,11.4,2992547.0,5.86,5.31,98.0,0.696
26,73.5,279.142931,15.0,10.8,311487.0,6.12,5.16,98.0,0.685
27,73.0,2416.588235,17.0,10.9,326939.0,6.38,4.54,99.0,0.681
28,72.8,189.681557,18.0,10.7,339616.0,6.27,4.29,97.0,0.674
29,73.3,1453.642777,15.0,10.7,3511.0,6.30,3.73,96.0,0.670

In [33]:
print(data_imputed.isnull().sum())

Life expectancy                    0
GDP                                0
Adult Mortality                    0
Schooling                          0
Population                         0
Total expenditure                  0
Alcohol                            0
Hepatitis B                        0
Income composition of resources    0
dtype: int64

# Exercise 2
Use MICE on the Planets (seaborn) dataset to fill in missing values.

In [35]:
planets = sns.load_dataset('planets')
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [36]:
print(planets.isnull().sum())

method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [38]:
data_subset = planets[['orbital_period', 'mass', 'distance']]
data_subset = pd.get_dummies(data_subset, drop_first=True)
imputer = IterativeImputer(max_iter=10, random_state=0)
data_imputed = pd.DataFrame(imputer.fit_transform(data_subset), columns=data_subset.columns)

In [39]:
print("Original Data (with missing values):")
data_subset.head(30)

Original Data (with missing values):

    orbital_period    mass  distance
0       269.300000   7.100     77.40
1       874.774000   2.210     56.95
2       763.000000   2.600     19.84
3       326.030000  19.400    110.62
4       516.220000  10.500    119.47
5       185.840000   4.800     76.39
6      1773.400000   4.640     18.15
7       798.500000     NaN     21.41
8       993.300000  10.300     73.10
9       452.800000   1.990     74.79
10      883.000000   0.860     74.79
11      335.100000   9.880     39.43
12      479.100000   3.880     97.28
13     1078.000000   2.530     14.08
14     2391.000000   0.540     14.08
15    14002.000000   1.640     14.08
16        4.230785   0.472     15.36
17       14.651000   0.800     12.53
18       44.380000   0.165     12.53
19     4909.000000   3.530     12.53
20        0.736540     NaN     12.53
21      261.200000   0.172     12.53
22        4.215000   0.016      8.52
23       38.021000   0.057      8.52
24      123.010000   0.072      8.52
25      116.688400     NaN     18.11
26      691.900000     NaN     81.50
27      952.700000   5.300     97.18
28      181.400000   3.200     45.52
29             NaN     NaN     45.52

In [40]:
print("\nData after MICE Imputation:")
data_imputed.head(30)

Data after MICE Imputation:

    orbital_period       mass  distance
0       269.300000   7.100000     77.40
1       874.774000   2.210000     56.95
2       763.000000   2.600000     19.84
3       326.030000  19.400000    110.62
4       516.220000  10.500000    119.47
5       185.840000   4.800000     76.39
6      1773.400000   4.640000     18.15
7       798.500000   1.839160     21.41
8       993.300000  10.300000     73.10
9       452.800000   1.990000     74.79
10      883.000000   0.860000     74.79
11      335.100000   9.880000     39.43
12      479.100000   3.880000     97.28
13     1078.000000   2.530000     14.08
14     2391.000000   0.540000     14.08
15    14002.000000   1.640000     14.08
16        4.230785   0.472000     15.36
17       14.651000   0.800000     12.53
18       44.380000   0.165000     12.53
19     4909.000000   3.530000     12.53
20        0.736540   1.268192     12.53
21      261.200000   0.172000     12.53
22        4.215000   0.016000      8.52
23       38.021000   0.057000      8.52
24      123.010000   0.072000      8.52
25      116.688400   1.442148     18.11
26      691.900000   3.062421     81.50
27      952.700000   5.300000     97.18
28      181.400000   3.200000     45.52
29     2043.064937   2.947431     45.52

In [41]:
print(data_imputed.isnull().sum())

orbital_period    0
mass              0
distance          0
dtype: int64